//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _54d8c47b03839 {
            get {
                object obj = ResourceManager.GetObject("_54d8c47b03839", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackGroundImage {
            get {
                object obj = ResourceManager.GetObject("BackGroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap border {
            get {
                object obj = ResourceManager.GetObject("border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn053_02 {
            get {
                object obj = ResourceManager.GetObject("btn053_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn053_10 {
            get {
                object obj = ResourceManager.GetObject("btn053_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバールール
        ///
        ///サーバーに参加する前に
        ///必ず目を通しておいてください
        ///
        ///　はじめに
        ///・禁止事項に抵触した方は，BAN（永久追放）になる場合があります。
        ///・基本的に，荒らし被害，巻戻り，その他による補償は一切ありません。
        ///・トラブル（PKなど）が発生した場合は，すぐに報告して下さい。
        ///　時間が経つ程，問題解決は難しくなります。
        ///・バグ等を発見した場合は，必ずプライベートチャットまたはメール機能を利用し
        ///　，連絡してください
        ///・サーバールールは不定期に追加・変更されますので，
        ///　定期的に確認するようにしましょう。
        ///　また，変更等あった場合はゲーム内チャットでの呼び掛けをお願いします。
        ///　基本
        ///・土地の所有者が分かりやすいように，
        ///　共同生活者全員のプレーヤー名を書いた看板を建物などに貼りましょう。
        ///・拠点は各ワールド毎に1ヶ所とする。仮拠点も可
        ///・新たに拠点を設ける場合は，他プレーヤーの拠点から最低250m離して建設すること。
        ///・ルールを守らない場合は，設置物を強制的に撤去します
        ///・不定期にスタッフが各拠点を見回ります。その際ルールに違反しているのを確認した場合
        ///即時 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string caption {
            get {
                return ResourceManager.GetString("caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap frontia_top {
            get {
                object obj = ResourceManager.GetObject("frontia_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap label {
            get {
                object obj = ResourceManager.GetObject("label", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◆【終了】[2015/06/28 12:00～17:15]
        ///　　●このメンテナンスの更新
        ///　　　　　・ハードコアの為のデスカウントリセット
        ///　　　　　・以下のMODを削除しました
        ///　　　　　　　　├ AbyssalCraft
        ///　　　　　　　　├ Mo Creatures
        ///　　　　　　　　└ TwilightForest
        ///　　　　　・以下のMODを追加しました
        ///　　　　　　　　├ bdlib
        ///　　　　　　　　├ FluidityFoodstuffs
        ///　　　　　　　　├ Gendustry
        ///　　　　　　　　├ Advanced Generators
        ///　　　　　　　　└ MagicBees
        ///　　　　　・他MOD更新
        ///
        ///◆【終了】[2015/05/17 11:00～12:00]
        ///　　●IC2不具合修正　
        ///　　　　　　Fix：サーバーのバージョンアップで修正されました
        ///　　　　　　　　　└正常に終了しました
        ///
        ///◆【終了】緊急メンテナンス[2015/05/08 13:00～14:00]
        ///　　●機械掘り資源ワールドの再生成
        ///　　　　　　　　　　└終了しました
        ///
        ///◆【終了】[2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mainte_frontia {
            get {
                return ResourceManager.GetString("mainte_frontia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ●[2015/06/28]
        ///　　☆MOD更新
        ///　　　　├　minecraft forgeを１４２８以降に
        ///　　　　├　以下のMODを削除しました
        ///　　　　│　　　　├ AbyssalCraft
        ///　　　　│　　　　├ Mo Creatures
        ///　　　　│　　　　└ TwilightForest
        ///　　　　└　以下のMODを追加しました
        ///　　　　　　　　　├ bdlib
        ///　　　　　　　　　├ FluidityFoodstuffs
        ///　　　　　　　　　├ Gendustry
        ///　　　　　　　　　├ Advanced Generators
        ///　　　　　　　　　└ MagicBees
        ///　　　　　　・他MOD更新
        ///●[2015/05/05]
        ///　　☆MOD更新予定
        ///　　　　├　Forgeを１３８１に更新
        ///　　　　└　他多数MOD更新
        ///●[2015/04/06]
        ///　　☆以下のMODを追加しました
        ///　　　　├　OpenBlocks
        ///　　　　└　MFRAddon 他
        ///　　☆その他MOD更新
        ///
        ///●[2015/03/29]
        ///　　☆以下のMODを追加しました
        ///　　　　└　Balkon&apos;s W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modUpdate_frontia {
            get {
                return ResourceManager.GetString("modUpdate_frontia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topst {
            get {
                object obj = ResourceManager.GetObject("topst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ver {
            get {
                object obj = ResourceManager.GetObject("ver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
